In [8]:
ipcluster start

SyntaxError: invalid syntax (<ipython-input-8-c3b45a92cbf7>, line 1)

In [14]:
from IPython.parallel import Client
engines = parallel . Client ()
engines . block = True
print (engines . ids)


NameError: name 'parallel' is not defined

In [5]:
engines [0]. execute ( "a = 2")
engines [0]. execute ( "b = 10")
engines [0]. execute ( "c = a + b ")

NameError: name 'engines' is not defined

In [18]:
engines [0]. pull ( "c" )

12

In [24]:
engines [0]. execute ("a = 2")
engines [0]. execute ( "b = 10")
engines [1]. execute ( "a = 9" )
engines [1]. execute ( "b = 7" )
engines [0:2]. execute ( "c = a + b" )

<AsyncResult: execute:finished>

In [25]:
engines [0:2]. pull ( "c" )

[12, 16]

In [26]:
dview2 = engines [0:2]
dview = engines . direct_view ()

In [51]:
import numpy as np

In [64]:
A0 = np.array([[1,2,3],[6,4,2]])
A1 = np.array([[8,2],[1,4],[2,1]])
B0 = A0.T
B1 = A1.T
print(B0)
print(B1)

[[1 6]
 [2 4]
 [3 2]]
[[8 1 2]
 [2 4 1]]


In [ ]:
dview2 . execute ( 'import numpy as np')
engines [0]. push ( dict (A=A0 , B= B0 ))
engines [1]. push ( dict (A=A1 , B= B1 ))
dview2 . execute ( "C = np . dot (A ,B)")
dview2 . pull ( "C")